# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\hauptfenster.ui'
#
# Created: Thu Mar 27 20:44:04 2014
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1020, 620)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/bilder/processor.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 20, 81, 31))
        self.label.setStyleSheet("color: rgb(85, 170, 0);\n"
"font-size: 20px;\n"
"font-weight: 800;")
        self.label.setObjectName("label")
        self.pushButtonProzess = QtGui.QPushButton(self.centralwidget)
        self.pushButtonProzess.setGeometry(QtCore.QRect(60, 140, 111, 101))
        self.pushButtonProzess.setStyleSheet("")
        self.pushButtonProzess.setObjectName("pushButtonProzess")
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(310, 80, 321, 431))
        self.groupBox.setObjectName("groupBox")
        self.groupBoxAssistenten = QtGui.QGroupBox(self.groupBox)
        self.groupBoxAssistenten.setGeometry(QtCore.QRect(20, 30, 281, 81))
        self.groupBoxAssistenten.setObjectName("groupBoxAssistenten")
        self.label_22 = QtGui.QLabel(self.groupBoxAssistenten)
        self.label_22.setGeometry(QtCore.QRect(15, 20, 51, 20))
        self.label_22.setObjectName("label_22")
        self.labelAnzahlAssitenten = QtGui.QLabel(self.groupBoxAssistenten)
        self.labelAnzahlAssitenten.setGeometry(QtCore.QRect(15, 50, 41, 20))
        self.labelAnzahlAssitenten.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelAnzahlAssitenten.setObjectName("labelAnzahlAssitenten")
        self.label_24 = QtGui.QLabel(self.groupBoxAssistenten)
        self.label_24.setGeometry(QtCore.QRect(75, 20, 101, 20))
        self.label_24.setObjectName("label_24")
        self.label_25 = QtGui.QLabel(self.groupBoxAssistenten)
        self.label_25.setGeometry(QtCore.QRect(195, 20, 81, 20))
        self.label_25.setObjectName("label_25")
        self.labelAssistentenProzesseProSekunde = QtGui.QLabel(self.groupBoxAssistenten)
        self.labelAssistentenProzesseProSekunde.setGeometry(QtCore.QRect(95, 50, 71, 20))
        self.labelAssistentenProzesseProSekunde.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelAssistentenProzesseProSekunde.setObjectName("labelAssistentenProzesseProSekunde")
        self.labelAssistentenProzesseGesammt = QtGui.QLabel(self.groupBoxAssistenten)
        self.labelAssistentenProzesseGesammt.setGeometry(QtCore.QRect(195, 50, 71, 20))
        self.labelAssistentenProzesseGesammt.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelAssistentenProzesseGesammt.setObjectName("labelAssistentenProzesseGesammt")
        self.groupBoxDOS = QtGui.QGroupBox(self.groupBox)
        self.groupBoxDOS.setGeometry(QtCore.QRect(20, 130, 281, 81))
        self.groupBoxDOS.setObjectName("groupBoxDOS")
        self.label_28 = QtGui.QLabel(self.groupBoxDOS)
        self.label_28.setGeometry(QtCore.QRect(15, 20, 51, 20))
        self.label_28.setObjectName("label_28")
        self.labelAnzahlDOS = QtGui.QLabel(self.groupBoxDOS)
        self.labelAnzahlDOS.setGeometry(QtCore.QRect(15, 50, 41, 20))
        self.labelAnzahlDOS.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelAnzahlDOS.setObjectName("labelAnzahlDOS")
        self.label_30 = QtGui.QLabel(self.groupBoxDOS)
        self.label_30.setGeometry(QtCore.QRect(75, 20, 101, 20))
        self.label_30.setObjectName("label_30")
        self.label_31 = QtGui.QLabel(self.groupBoxDOS)
        self.label_31.setGeometry(QtCore.QRect(195, 20, 81, 20))
        self.label_31.setObjectName("label_31")
        self.labelDOSProzesseProSekunde = QtGui.QLabel(self.groupBoxDOS)
        self.labelDOSProzesseProSekunde.setGeometry(QtCore.QRect(95, 50, 71, 20))
        self.labelDOSProzesseProSekunde.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelDOSProzesseProSekunde.setObjectName("labelDOSProzesseProSekunde")
        self.labelDOSProzesseGesammt = QtGui.QLabel(self.groupBoxDOS)
        self.labelDOSProzesseGesammt.setGeometry(QtCore.QRect(195, 50, 71, 20))
        self.labelDOSProzesseGesammt.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelDOSProzesseGesammt.setObjectName("labelDOSProzesseGesammt")
        self.groupBoxServer = QtGui.QGroupBox(self.groupBox)
        self.groupBoxServer.setGeometry(QtCore.QRect(20, 230, 281, 81))
        self.groupBoxServer.setObjectName("groupBoxServer")
        self.label_34 = QtGui.QLabel(self.groupBoxServer)
        self.label_34.setGeometry(QtCore.QRect(15, 20, 51, 20))
        self.label_34.setObjectName("label_34")
        self.labelAnzahlServer = QtGui.QLabel(self.groupBoxServer)
        self.labelAnzahlServer.setGeometry(QtCore.QRect(15, 50, 41, 20))
        self.labelAnzahlServer.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelAnzahlServer.setObjectName("labelAnzahlServer")
        self.label_36 = QtGui.QLabel(self.groupBoxServer)
        self.label_36.setGeometry(QtCore.QRect(75, 20, 101, 20))
        self.label_36.setObjectName("label_36")
        self.label_37 = QtGui.QLabel(self.groupBoxServer)
        self.label_37.setGeometry(QtCore.QRect(195, 20, 81, 20))
        self.label_37.setObjectName("label_37")
        self.labelServerProzesseProSekunde = QtGui.QLabel(self.groupBoxServer)
        self.labelServerProzesseProSekunde.setGeometry(QtCore.QRect(95, 50, 71, 20))
        self.labelServerProzesseProSekunde.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelServerProzesseProSekunde.setObjectName("labelServerProzesseProSekunde")
        self.labelServerProzesseGesammt = QtGui.QLabel(self.groupBoxServer)
        self.labelServerProzesseGesammt.setGeometry(QtCore.QRect(195, 50, 71, 20))
        self.labelServerProzesseGesammt.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelServerProzesseGesammt.setObjectName("labelServerProzesseGesammt")
        self.groupBoxMatrix = QtGui.QGroupBox(self.groupBox)
        self.groupBoxMatrix.setGeometry(QtCore.QRect(20, 330, 281, 81))
        self.groupBoxMatrix.setObjectName("groupBoxMatrix")
        self.label_40 = QtGui.QLabel(self.groupBoxMatrix)
        self.label_40.setGeometry(QtCore.QRect(15, 20, 51, 20))
        self.label_40.setObjectName("label_40")
        self.labelAnzahlMatrix = QtGui.QLabel(self.groupBoxMatrix)
        self.labelAnzahlMatrix.setGeometry(QtCore.QRect(15, 50, 41, 20))
        self.labelAnzahlMatrix.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelAnzahlMatrix.setObjectName("labelAnzahlMatrix")
        self.label_42 = QtGui.QLabel(self.groupBoxMatrix)
        self.label_42.setGeometry(QtCore.QRect(75, 20, 101, 20))
        self.label_42.setObjectName("label_42")
        self.label_43 = QtGui.QLabel(self.groupBoxMatrix)
        self.label_43.setGeometry(QtCore.QRect(195, 20, 81, 20))
        self.label_43.setObjectName("label_43")
        self.labelMatrixProzesseProSekunde = QtGui.QLabel(self.groupBoxMatrix)
        self.labelMatrixProzesseProSekunde.setGeometry(QtCore.QRect(95, 50, 71, 20))
        self.labelMatrixProzesseProSekunde.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelMatrixProzesseProSekunde.setObjectName("labelMatrixProzesseProSekunde")
        self.labelMatrixProzesseGesammt = QtGui.QLabel(self.groupBoxMatrix)
        self.labelMatrixProzesseGesammt.setGeometry(QtCore.QRect(195, 50, 71, 20))
        self.labelMatrixProzesseGesammt.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelMatrixProzesseGesammt.setObjectName("labelMatrixProzesseGesammt")
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(660, 80, 321, 431))
        self.groupBox_2.setObjectName("groupBox_2")
        self.frameAssistent = QtGui.QFrame(self.groupBox_2)
        self.frameAssistent.setGeometry(QtCore.QRect(10, 30, 291, 81))
        self.frameAssistent.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frameAssistent.setFrameShadow(QtGui.QFrame.Raised)
        self.frameAssistent.setObjectName("frameAssistent")
        self.pushButtonAssistentHinzufuegen = QtGui.QPushButton(self.frameAssistent)
        self.pushButtonAssistentHinzufuegen.setGeometry(QtCore.QRect(10, 30, 131, 41))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/bilder/assistent.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonAssistentHinzufuegen.setIcon(icon1)
        self.pushButtonAssistentHinzufuegen.setIconSize(QtCore.QSize(32, 32))
        self.pushButtonAssistentHinzufuegen.setObjectName("pushButtonAssistentHinzufuegen")
        self.label_4 = QtGui.QLabel(self.frameAssistent)
        self.label_4.setGeometry(QtCore.QRect(10, 10, 71, 16))
        self.label_4.setObjectName("label_4")
        self.labelPreisAssistent = QtGui.QLabel(self.frameAssistent)
        self.labelPreisAssistent.setGeometry(QtCore.QRect(200, 10, 81, 20))
        self.labelPreisAssistent.setObjectName("labelPreisAssistent")
        self.labelProduktionAssistent = QtGui.QLabel(self.frameAssistent)
        self.labelProduktionAssistent.setGeometry(QtCore.QRect(200, 50, 71, 16))
        self.labelProduktionAssistent.setObjectName("labelProduktionAssistent")
        self.frameDOS = QtGui.QFrame(self.groupBox_2)
        self.frameDOS.setGeometry(QtCore.QRect(10, 120, 291, 81))
        self.frameDOS.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frameDOS.setFrameShadow(QtGui.QFrame.Raised)
        self.frameDOS.setObjectName("frameDOS")
        self.pushButtonDOSHinzufuegen = QtGui.QPushButton(self.frameDOS)
        self.pushButtonDOSHinzufuegen.setGeometry(QtCore.QRect(10, 30, 131, 41))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/bilder/dos.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonDOSHinzufuegen.setIcon(icon2)
        self.pushButtonDOSHinzufuegen.setIconSize(QtCore.QSize(32, 32))
        self.pushButtonDOSHinzufuegen.setObjectName("pushButtonDOSHinzufuegen")
        self.label_7 = QtGui.QLabel(self.frameDOS)
        self.label_7.setGeometry(QtCore.QRect(10, 10, 71, 16))
        self.label_7.setObjectName("label_7")
        self.labelPreisDOS = QtGui.QLabel(self.frameDOS)
        self.labelPreisDOS.setGeometry(QtCore.QRect(200, 10, 81, 20))
        self.labelPreisDOS.setObjectName("labelPreisDOS")
        self.labelProduktionDOS = QtGui.QLabel(self.frameDOS)
        self.labelProduktionDOS.setGeometry(QtCore.QRect(200, 50, 71, 16))
        self.labelProduktionDOS.setObjectName("labelProduktionDOS")
        self.frameServer = QtGui.QFrame(self.groupBox_2)
        self.frameServer.setGeometry(QtCore.QRect(10, 220, 291, 81))
        self.frameServer.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frameServer.setFrameShadow(QtGui.QFrame.Raised)
        self.frameServer.setObjectName("frameServer")
        self.pushButtonServerHinzufuegen = QtGui.QPushButton(self.frameServer)
        self.pushButtonServerHinzufuegen.setGeometry(QtCore.QRect(10, 30, 131, 41))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/bilder/server.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonServerHinzufuegen.setIcon(icon3)
        self.pushButtonServerHinzufuegen.setIconSize(QtCore.QSize(32, 32))
        self.pushButtonServerHinzufuegen.setObjectName("pushButtonServerHinzufuegen")
        self.label_10 = QtGui.QLabel(self.frameServer)
        self.label_10.setGeometry(QtCore.QRect(10, 10, 71, 16))
        self.label_10.setObjectName("label_10")
        self.labelPreisServer = QtGui.QLabel(self.frameServer)
        self.labelPreisServer.setGeometry(QtCore.QRect(200, 10, 81, 20))
        self.labelPreisServer.setObjectName("labelPreisServer")
        self.labelProduktionServer = QtGui.QLabel(self.frameServer)
        self.labelProduktionServer.setGeometry(QtCore.QRect(200, 50, 81, 16))
        self.labelProduktionServer.setObjectName("labelProduktionServer")
        self.frameMatrix = QtGui.QFrame(self.groupBox_2)
        self.frameMatrix.setGeometry(QtCore.QRect(10, 320, 291, 81))
        self.frameMatrix.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frameMatrix.setFrameShadow(QtGui.QFrame.Raised)
        self.frameMatrix.setObjectName("frameMatrix")
        self.pushButtonMatrixHinzufuegen = QtGui.QPushButton(self.frameMatrix)
        self.pushButtonMatrixHinzufuegen.setGeometry(QtCore.QRect(10, 30, 131, 41))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/bilder/matrix.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonMatrixHinzufuegen.setIcon(icon4)
        self.pushButtonMatrixHinzufuegen.setIconSize(QtCore.QSize(32, 32))
        self.pushButtonMatrixHinzufuegen.setObjectName("pushButtonMatrixHinzufuegen")
        self.label_19 = QtGui.QLabel(self.frameMatrix)
        self.label_19.setGeometry(QtCore.QRect(10, 10, 71, 16))
        self.label_19.setObjectName("label_19")
        self.labelPreisMatrix = QtGui.QLabel(self.frameMatrix)
        self.labelPreisMatrix.setGeometry(QtCore.QRect(200, 10, 81, 20))
        self.labelPreisMatrix.setObjectName("labelPreisMatrix")
        self.labelProduktionMatrix = QtGui.QLabel(self.frameMatrix)
        self.labelProduktionMatrix.setGeometry(QtCore.QRect(190, 50, 91, 20))
        self.labelProduktionMatrix.setObjectName("labelProduktionMatrix")
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 70, 111, 16))
        self.label_2.setObjectName("label_2")
        self.labelProzesseProSekunde = QtGui.QLabel(self.centralwidget)
        self.labelProzesseProSekunde.setGeometry(QtCore.QRect(150, 70, 101, 20))
        self.labelProzesseProSekunde.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelProzesseProSekunde.setObjectName("labelProzesseProSekunde")
        self.labelScore = QtGui.QLabel(self.centralwidget)
        self.labelScore.setGeometry(QtCore.QRect(130, 30, 121, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.labelScore.setFont(font)
        self.labelScore.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelScore.setObjectName("labelScore")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1020, 21))
        self.menubar.setObjectName("menubar")
        self.menuDatei = QtGui.QMenu(self.menubar)
        self.menuDatei.setObjectName("menuDatei")
        self.menuInfo = QtGui.QMenu(self.menubar)
        self.menuInfo.setObjectName("menuInfo")
        self.menuHilfe = QtGui.QMenu(self.menuInfo)
        self.menuHilfe.setObjectName("menuHilfe")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionNeues_Spiel = QtGui.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/start.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNeues_Spiel.setIcon(icon5)
        self.actionNeues_Spiel.setObjectName("actionNeues_Spiel")
        self.actionSpiel_speichern = QtGui.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/speichern.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSpiel_speichern.setIcon(icon6)
        self.actionSpiel_speichern.setObjectName("actionSpiel_speichern")
        self.actionSpiel_laden = QtGui.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/laden.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSpiel_laden.setIcon(icon7)
        self.actionSpiel_laden.setObjectName("actionSpiel_laden")
        self.actionBeenden = QtGui.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/beenden.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionBeenden.setIcon(icon8)
        self.actionBeenden.setObjectName("actionBeenden")
        self.actionAnleitung = QtGui.QAction(MainWindow)
        self.actionAnleitung.setObjectName("actionAnleitung")
        self.actionOnline_Dokumentation = QtGui.QAction(MainWindow)
        self.actionOnline_Dokumentation.setObjectName("actionOnline_Dokumentation")
        self.actionUeber = QtGui.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icons/ueber.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionUeber.setIcon(icon9)
        self.actionUeber.setObjectName("actionUeber")
        self.menuDatei.addAction(self.actionNeues_Spiel)
        self.menuDatei.addSeparator()
        self.menuDatei.addAction(self.actionSpiel_speichern)
        self.menuDatei.addAction(self.actionSpiel_laden)
        self.menuDatei.addSeparator()
        self.menuDatei.addAction(self.actionBeenden)
        self.menuHilfe.addAction(self.actionAnleitung)
        self.menuHilfe.addAction(self.actionOnline_Dokumentation)
        self.menuInfo.addAction(self.menuHilfe.menuAction())
        self.menuInfo.addAction(self.actionUeber)
        self.menubar.addAction(self.menuDatei.menuAction())
        self.menubar.addAction(self.menuInfo.menuAction())
        self.toolBar.addAction(self.actionNeues_Spiel)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionSpiel_speichern)
        self.toolBar.addAction(self.actionSpiel_laden)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Score:", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonProzess.setText(QtGui.QApplication.translate("MainWindow", "Prozess starten", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Besitztümer", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBoxAssistenten.setTitle(QtGui.QApplication.translate("MainWindow", "Assistenten:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("MainWindow", "Anzahl:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelAnzahlAssitenten.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setText(QtGui.QApplication.translate("MainWindow", "Prozesse / Sekunde:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setText(QtGui.QApplication.translate("MainWindow", "Prozesse ges.:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelAssistentenProzesseProSekunde.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.labelAssistentenProzesseGesammt.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBoxDOS.setTitle(QtGui.QApplication.translate("MainWindow", "DOS:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_28.setText(QtGui.QApplication.translate("MainWindow", "Anzahl:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelAnzahlDOS.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_30.setText(QtGui.QApplication.translate("MainWindow", "Prozesse / Sekunde:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_31.setText(QtGui.QApplication.translate("MainWindow", "Prozesse ges.:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelDOSProzesseProSekunde.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.labelDOSProzesseGesammt.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBoxServer.setTitle(QtGui.QApplication.translate("MainWindow", "Server:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_34.setText(QtGui.QApplication.translate("MainWindow", "Anzahl:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelAnzahlServer.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_36.setText(QtGui.QApplication.translate("MainWindow", "Prozesse / Sekunde:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_37.setText(QtGui.QApplication.translate("MainWindow", "Prozesse ges.:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelServerProzesseProSekunde.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.labelServerProzesseGesammt.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBoxMatrix.setTitle(QtGui.QApplication.translate("MainWindow", "Matrix:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_40.setText(QtGui.QApplication.translate("MainWindow", "Anzahl:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelAnzahlMatrix.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_42.setText(QtGui.QApplication.translate("MainWindow", "Prozesse / Sekunde:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_43.setText(QtGui.QApplication.translate("MainWindow", "Prozesse ges.:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelMatrixProzesseProSekunde.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.labelMatrixProzesseGesammt.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("MainWindow", "Baumenü", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonAssistentHinzufuegen.setText(QtGui.QApplication.translate("MainWindow", "hinzufügen", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Assistent", None, QtGui.QApplication.UnicodeUTF8))
        self.labelPreisAssistent.setText(QtGui.QApplication.translate("MainWindow", "Preis:  $ 100", None, QtGui.QApplication.UnicodeUTF8))
        self.labelProduktionAssistent.setText(QtGui.QApplication.translate("MainWindow", "+1 / Sekunde", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonDOSHinzufuegen.setText(QtGui.QApplication.translate("MainWindow", "hinzufügen", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "DOS", None, QtGui.QApplication.UnicodeUTF8))
        self.labelPreisDOS.setText(QtGui.QApplication.translate("MainWindow", "Preis:  $ 500", None, QtGui.QApplication.UnicodeUTF8))
        self.labelProduktionDOS.setText(QtGui.QApplication.translate("MainWindow", "+30 / Sekunde", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonServerHinzufuegen.setText(QtGui.QApplication.translate("MainWindow", "hinzufügen", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "Server", None, QtGui.QApplication.UnicodeUTF8))
        self.labelPreisServer.setText(QtGui.QApplication.translate("MainWindow", "Preis:  $ 5000", None, QtGui.QApplication.UnicodeUTF8))
        self.labelProduktionServer.setText(QtGui.QApplication.translate("MainWindow", "+200 / Sekunde", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonMatrixHinzufuegen.setText(QtGui.QApplication.translate("MainWindow", "hinzufügen", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("MainWindow", "Matrix", None, QtGui.QApplication.UnicodeUTF8))
        self.labelPreisMatrix.setText(QtGui.QApplication.translate("MainWindow", "Preis:  $ 25000", None, QtGui.QApplication.UnicodeUTF8))
        self.labelProduktionMatrix.setText(QtGui.QApplication.translate("MainWindow", "+2500 / Sekunde", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Prozesse / Sekunde:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelProzesseProSekunde.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.labelScore.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.menuDatei.setTitle(QtGui.QApplication.translate("MainWindow", "Datei", None, QtGui.QApplication.UnicodeUTF8))
        self.menuInfo.setTitle(QtGui.QApplication.translate("MainWindow", "Info", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHilfe.setTitle(QtGui.QApplication.translate("MainWindow", "Hilfe", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("MainWindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNeues_Spiel.setText(QtGui.QApplication.translate("MainWindow", "Neues Spiel", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNeues_Spiel.setToolTip(QtGui.QApplication.translate("MainWindow", "Neues Spiel", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNeues_Spiel.setStatusTip(QtGui.QApplication.translate("MainWindow", "Neues Spiel starten.", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNeues_Spiel.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+N", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSpiel_speichern.setText(QtGui.QApplication.translate("MainWindow", "Spiel speichern", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSpiel_speichern.setStatusTip(QtGui.QApplication.translate("MainWindow", "Spiel speichern.", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSpiel_speichern.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+S", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSpiel_laden.setText(QtGui.QApplication.translate("MainWindow", "Spiel laden", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSpiel_laden.setStatusTip(QtGui.QApplication.translate("MainWindow", "Spiel laden.", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSpiel_laden.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+L", None, QtGui.QApplication.UnicodeUTF8))
        self.actionBeenden.setText(QtGui.QApplication.translate("MainWindow", "Beenden", None, QtGui.QApplication.UnicodeUTF8))
        self.actionBeenden.setStatusTip(QtGui.QApplication.translate("MainWindow", "Programm beenden.", None, QtGui.QApplication.UnicodeUTF8))
        self.actionBeenden.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAnleitung.setText(QtGui.QApplication.translate("MainWindow", "Anleitung", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOnline_Dokumentation.setText(QtGui.QApplication.translate("MainWindow", "Online-Dokumentation", None, QtGui.QApplication.UnicodeUTF8))
        self.actionUeber.setText(QtGui.QApplication.translate("MainWindow", "Über", None, QtGui.QApplication.UnicodeUTF8))
        self.actionUeber.setStatusTip(QtGui.QApplication.translate("MainWindow", "Informationen über das Programm.", None, QtGui.QApplication.UnicodeUTF8))

import icons_rc
